apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: animation-production-tracker
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Cloud Run configuration
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
        # Cloud SQL connection
        run.googleapis.com/cloudsql-instances: thebreakfastfam:us-central1:animation-db
    spec:
      # Container concurrency
      containerConcurrency: 80
      # Request timeout (15 minutes max)
      timeoutSeconds: 900
      serviceAccountName: animation-tracker-sa@thebreakfastfam.iam.gserviceaccount.com
      containers:
      - image: gcr.io/thebreakfastfam/animation-tracker:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        # Application settings
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "8080"
        - name: PROJECT_ID
          value: thebreakfastfam
        - name: REGION
          value: us-central1
        
        # Database settings
        - name: DB_HOST
          value: "/cloudsql/thebreakfastfam:us-central1:animation-db"
        - name: DB_NAME
          value: production_tracker
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_PORT
          value: "5432"
        
        # Sync configuration
        - name: NGROK_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: sync-config
              key: webhook-secret
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: sync-config
              key: webhook-secret
        - name: STORAGE_BUCKET_NAME
          value: thebreakfastfam-production-files
        
        # Feature flags
        - name: ENABLE_CLOUD_SYNC
          value: "true"
        - name: ENABLE_LOCAL_EXCEL
          value: "true"
        - name: AUTO_BACKUP_EXCEL
          value: "true"
        
        # Resource limits
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        
        # Startup and liveness probes
        startupProbe:
          httpGet:
            path: /api/debug
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
          periodSeconds: 10
        
        livenessProbe:
          httpGet:
            path: /api/debug
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          periodSeconds: 30
        
        readinessProbe:
          httpGet:
            path: /api/debug
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          periodSeconds: 10